export const GET_COURSE_ANNOUNCEMENTS = "GET_COURSE_ANNOUNCEMENTS";
export const POST_ANNOUNCEMENT = "POST_ANNOUNCEMENT";
export const PUT_ANNOUNCEMENT = "PUT_ANNOUNCEMENT";
export const DELETE_ANNOUNCEMENT = "DELETE_ANNOUNCEMENT";
export const POST_ANNOUNCEMENT_READ = "POST_ANNOUNCEMENT_READ";

