export const GET_ASSIGNMENTS = "GET_ASSIGNMENTS";
export const GET_ASSIGNMENT_BY_ID = "GET_ASSIGNMENT_BY_ID";
export const GET_ASSIGNMENTS_BY_COURSE = "GET_ASSIGNMENTS_BY_COURSE";
export const POST_ASSIGNMENT = "POST_ASSIGNMENT";
export const PUT_ASSIGNMENT = "PUT_ASSIGNMENT";
export const GET_ASSIGNMENT_SUBMISSIONS = "GET_ASSIGNMENT_SUBMISSIONS";
export const GET_ASSIGNMENT_SUBMISSIONS_ME = "GET_ASSIGNMENT_SUBMISSIONS_ME";
export const GET_ASSIGNMENT_SUBMISSIONS_BY_COURSE = "GET_ASSIGNMENT_SUBMISSIONS_BY_COURSE";
export const POST_ASSIGNMENT_SUBMIT = "POST_ASSIGNMENT_SUBMIT";

