export const GET_AUTH_ME = "GET_AUTH_ME";
export const POST_AUTH_LOGIN = "POST_AUTH_LOGIN";
export const POST_AUTH_REGISTER = "POST_AUTH_REGISTER";
export const POST_AUTH_FORGOT_PASSWORD = "POST_AUTH_FORGOT_PASSWORD";
export const POST_AUTH_RESET_PASSWORD = "POST_AUTH_RESET_PASSWORD";

