export const GET_EXAMS = "GET_EXAMS";
export const GET_EXAM_BY_ID = "GET_EXAM_BY_ID";
export const GET_EXAM_QUESTIONS = "GET_EXAM_QUESTIONS";
export const POST_EXAM = "POST_EXAM";
export const PUT_EXAM = "PUT_EXAM";
export const DELETE_EXAM = "DELETE_EXAM";
export const POST_EXAM_QUESTION = "POST_EXAM_QUESTION";
export const PUT_EXAM_QUESTION = "PUT_EXAM_QUESTION";
export const DELETE_EXAM_QUESTION = "DELETE_EXAM_QUESTION";
export const POST_EXAM_SUBMIT = "POST_EXAM_SUBMIT";
export const GET_EXAM_SUBMISSION = "GET_EXAM_SUBMISSION";
export const GET_EXAM_SUBMISSIONS_BY_COURSE = "GET_EXAM_SUBMISSIONS_BY_COURSE";
export const PUT_EXAM_GRADE_SUBMISSION = "PUT_EXAM_GRADE_SUBMISSION";

