export const GET_INSTRUCTOR_PROFILE = "GET_INSTRUCTOR_PROFILE";
export const PUT_INSTRUCTOR_PROFILE = "PUT_INSTRUCTOR_PROFILE";
export const PUT_INSTRUCTOR_ACCOUNT = "PUT_INSTRUCTOR_ACCOUNT";
export const GET_INSTRUCTOR_DASHBOARD = "GET_INSTRUCTOR_DASHBOARD";
export const GET_INSTRUCTOR_COURSES = "GET_INSTRUCTOR_COURSES";

