export const GET_INSTITUTION_PROFILE_ME = "GET_INSTITUTION_PROFILE_ME";
export const PUT_INSTITUTION_PROFILE_ME = "PUT_INSTITUTION_PROFILE_ME";
export const GET_INSTITUTIONS = "GET_INSTITUTIONS";
export const GET_INSTITUTION_BY_ID = "GET_INSTITUTION_BY_ID";
export const GET_INSTITUTION_COURSES = "GET_INSTITUTION_COURSES";
export const GET_INSTITUTION_STATS_OVERVIEW = "GET_INSTITUTION_STATS_OVERVIEW";
export const GET_INSTITUTION_DASHBOARD = "GET_INSTITUTION_DASHBOARD";
export const GET_INSTITUTION_INSTRUCTORS_ALL = "GET_INSTITUTION_INSTRUCTORS_ALL";

