export const GET_PUBLIC_COURSES_TRENDING = "GET_PUBLIC_COURSES_TRENDING";
export const GET_PUBLIC_COURSES_BY_CATEGORY = "GET_PUBLIC_COURSES_BY_CATEGORY";
export const GET_PUBLIC_COURSES_CATEGORIES = "GET_PUBLIC_COURSES_CATEGORIES";
export const GET_PUBLIC_COURSES_SEARCH = "GET_PUBLIC_COURSES_SEARCH";
export const POST_PUBLIC_COURSE_ENROLL = "POST_PUBLIC_COURSE_ENROLL";

