export const GET_QUIZZES = "GET_QUIZZES";
export const GET_QUIZ_BY_ID = "GET_QUIZ_BY_ID";
export const GET_QUIZ_QUESTIONS = "GET_QUIZ_QUESTIONS";
export const POST_QUIZ = "POST_QUIZ";
export const PUT_QUIZ = "PUT_QUIZ";
export const DELETE_QUIZ = "DELETE_QUIZ";
export const POST_QUIZ_QUESTION = "POST_QUIZ_QUESTION";
export const PUT_QUIZ_QUESTION = "PUT_QUIZ_QUESTION";
export const DELETE_QUIZ_QUESTION = "DELETE_QUIZ_QUESTION";
export const POST_QUIZ_ATTEMPT = "POST_QUIZ_ATTEMPT";
export const POST_QUIZ_ATTEMPT_SUBMIT = "POST_QUIZ_ATTEMPT_SUBMIT";
export const GET_QUIZ_ATTEMPTS_USER = "GET_QUIZ_ATTEMPTS_USER";

