export const GET_STUDENT_PROFILE = "GET_STUDENT_PROFILE";
export const PUT_STUDENT_PROFILE = "PUT_STUDENT_PROFILE";
export const PUT_STUDENT_PASSWORD = "PUT_STUDENT_PASSWORD";
export const GET_STUDENT_ACCOUNT_OVERVIEW = "GET_STUDENT_ACCOUNT_OVERVIEW";
export const GET_STUDENT_ALERTS = "GET_STUDENT_ALERTS";
export const GET_STUDENT_DASHBOARD = "GET_STUDENT_DASHBOARD";
export const GET_STUDENT_NOTIFICATIONS = "GET_STUDENT_NOTIFICATIONS";
export const GET_STUDENT_CALENDAR = "GET_STUDENT_CALENDAR";
export const GET_STUDENT_COURSE_PROGRESS = "GET_STUDENT_COURSE_PROGRESS";
export const GET_STUDENT_COURSE_GRADES = "GET_STUDENT_COURSE_GRADES";
export const POST_STUDENT_LESSON_COMPLETE = "POST_STUDENT_LESSON_COMPLETE";
export const GET_STUDENT_ENROLLED_COURSES = "GET_STUDENT_ENROLLED_COURSES";
export const GET_STUDENT_SUBMISSIONS = "GET_STUDENT_SUBMISSIONS";

